# Generated by Django 4.1 on 2022-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('unit', models.IntegerField(blank=True, default=0)),
                ('category', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
            ],
        ),
    ]
